var pacientes = new Array ()
    
pacientes = [
{
    nombre : 'Claudia',
    apellido : 'Alvarez',
    edad : 29,
    diagnostico : 'Gripe',
    numero : 17,
},
{
    nombre : 'Iciar',
    apellido : 'Arjona',
    edad : 33,
    diagnostico : 'Embarazo',
    numero : 18,
},
{
    nombre : 'Violeta',
    apellido : 'Fernández',
    edad : 32,
    diagnostico : 'Talasemia',
    numero : 19,
},
{
    nombre : 'Juan Carlos',
    apellido : 'Morillas',
    edad : 29,
    diagnostico : 'Alzheimer',
    numero : 20,
},
{
    nombre : 'Elena',
    apellido : 'Cobo',
    edad : 31,
    diagnostico : 'Gripe',
    numero : 21,
},
{
    nombre : 'Vera',
    apellido : 'Arjona',
    edad : 3,
    diagnostico : 'Gripe',
    numero : 22,
},
{
    nombre : 'Mireia',
    apellido : 'Bru',
    edad : 24,
    diagnostico : 'Anemia',
    numero : 23,
},
{
    nombre : 'Laura',
    apellido : 'Arribas',
    edad : 32,
    diagnostico : 'Artrosis',
    numero : 25,
},
{
    nombre : 'Marta',
    apellido : 'Sintes',
    edad : 31,
    diagnostico : 'Anginas',
    numero : 26,
},
{
    nombre : 'Alicia',
    apellido : 'Escudero',
    edad : 31,
    diagnostico : 'Gripe',
    numero : 27,
},
{
    nombre : 'Carlota',
    apellido : 'Tortuero',
    edad : 30,
    diagnostico : 'Depresión',
    numero : 28,
},
{
    nombre : 'Dania',
    apellido : 'Rodriguez',
    edad : 36,
    diagnostico : 'Embarazo',
    numero : 29,
},
{
    nombre : 'Julia',
    apellido : 'Lopez',
    edad : 24,
    diagnostico : 'Afonía',
    numero : 30,
},
{
    nombre : 'Marta',
    apellido : 'Caballero',
    edad : 29,
    diagnostico : 'Gripe',
    numero : 31,
},
{
    nombre : 'Cristina',
    apellido : 'Munoz',
    edad : 30,
    diagnostico : 'Faringitis',
    numero : 32,
}
]